bookmark/urls.py
from django.urls import path
from .views import BookmarkListView, BookmarkCreateView, BookmarkDetailView, BookmarkUpdateView, BookmarkDeleteView

app_name = "bookmark"

urlpatterns = [
    path('', BookmarkListView.as_view(), name="list"),
    path('add/', BookmarkCreateView.as_view(), name="add"),    
    path('detail/<int:pk>/', BookmarkDetailView.as_view(), name="detail"), 
    path('update/<int:pk>/', BookmarkUpdateView.as_view(), name="update"),     
    path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name="delete"),      
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bookmark/models.py
from django.db import models
from django.urls import reverse

class Bookmark(models.Model):
    site_name = models.CharField(max_length = 200)
    description = models.CharField(max_length = 255, null=True, blank=True)
    url = models.URLField("Site URL")    

    def __str__(self,):
        return "사이트명 : {site_name}, 사이트주소 : {site_url}".format(site_name=self.site_name, site_url=self.url)       

    def get_absolute_url(self,):
        return reverse("bookmark:detail", args=[str(self.id)]) 


bookmark/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView


from .models import Bookmark

class BookmarkListView(ListView):
    model = Bookmark
    paginate_by = 5

class BookmarkCreateView(CreateView):
    model = Bookmark
    fields = ["site_name", "url"]
    success_url = reverse_lazy("bookmark:list")
    template_name_suffix = "_create"

class BookmarkDetailView(DetailView):
    model = Bookmark

class BookmarkUpdateView(UpdateView):
    model = Bookmark
    fields = ["site_name", "url"]
    template_name_suffix = "_update"

class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy("bookmark:list")

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}북마크 삭제{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">정말로 "{{ object }}" 삭제할까요?</div>
    <input type="submit" value="삭제" class="btn btn-danger">
   </form>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends "base.html" %}

{% block title %}북마크 생성{% endblock %}

{% block content %}    
   <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="추가" class="btn btn-info btn-sm">
   </form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}북마크 세부사항{% endblock %}

{% block content %}

    {{ object.site_name }}<br/>
    {{ object.url }}

{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}북마크 리스트{% endblock %}

{% block content %}

    <div class="btn-group">
        <a href="{% url 'bookmark:add' %}" class="btn btn-info">북마크 추가</a>
    </div>
    <p></p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Site</th>
                <th scope="col">URL</th>                
                <th scope="col">수정</th>
                <th scope="col">삭제</th>
            </tr>
        </thead>
        <tbody>
            {% for bookmark in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'bookmark:detail' pk=bookmark.id %}">{{ bookmark.site_name }}</a></td>
                <td><a href="{{ bookmark.url }}" target="_blank">{{ bookmark.url }}</a></td>
                <td><a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">수정</a></td>
                <td><a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">삭제</a></td>                                                                
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block pagination %}
    {% if is_paginated %}
        <ul class="pagination justify-content-center pagination-sm">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'bookmark:list' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>                    
                </li>
            {% endif %}

            {% for object in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == forloop.counter %} diabled {% endif %}">
                    <a class="page-link" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                </li>                
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'bookmark:list' %}?page={{ page_obj.next_page_number }}" tabindex="-1">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Next</a>                    
                </li>
            {% endif %}            
        </ul>
    {% endif %}
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends "base.html" %}

{% block title %}북마크 변경{% endblock %}

{% block content %}
   <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="변경" class="btn btn-info btn-sm">
   </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">    
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    

    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">장고 북마크 앱</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aira-expanded="false" aria-label="네비게이션 토글">
                <span class="navbar-toggle-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>
        <p></p>
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}    

                {% block pagination %}
                {% endblock %}
            </div>
        </div>
    </div>    
</body>
</html>